### ISSUE TITLE
Pass our own argument in when chat opens

### ISSUE THREAD

**Issue by abhiit61** [livechat/chat-window-android#1]
Hi,

I want to pass addition data to agent app with pre chat server data. So I create a local json file same as http://cdn.livechatinc.com/app/mobile/urls.json. I just appended my data as below.

https://secure.livechatinc.com/licence/8445821/open_chat.cgi?name=JohnDoe&email=test@test.test&params=visitor%3Duit

I build the jar again after this change and use it in my android app. But I can't see that additional field "visitor" anywhere in agent's app.

Can you tell me where is the problem here?

**Comment by Zhipeng-Chang** [comment]
Hi @abhiit61 ! I'm having the same issue as well? I wonder how did you handle this at the end? Thank you!

**Comment by nomyzs** [comment]
Hey @abhiit61 and @Zhipeng-Chang . 
Is that still an issue? I Just tested that and was able to see custom params in `Integrations data` section in Agent's Web App. Make sure to enable this section in Details options
https://www.livechatinc.com/help/custom-variables-configuration/#track-your-campaigns .
If the problem still occurs, feel free to open a new issue and provide steps to reproduce this issue. Thanks!
