### ISSUE TITLE
'we could not load' issue upon turning off then on the wifi/mobile data

### ISSUE THREAD

**Issue by aliayoub995** [livechat/chat-window-android#10]
Hello, I am facing an issue with the android sdk
Below is the scenario to reproduce it 

1- initialize the chat window and open it
2- fill all the required fields and start a new chat
3- minimize and open it several times(no problem)
4- turn off the wifi then instantly turn it on and the live chat window is always going to show we could not load
no matter how much I try to close and open the chat window
I have to initialize it again
and all the chat history is gone
We tried the same scenario on the iOS SDK and it is not happening

**Comment by nomyzs** [comment]
Hey @aliayoub995 
We have new build out that should help with your problem.
Our chat window currently handles internet issues pretty well, so you should not worry about that anymore. But introduced onError callback will give you full control on how and when to show error overlay.
Hope it helps!
