### ISSUE TITLE
Not input field for sending a message on API 18

### ISSUE THREAD

**Issue by kesarawimal** [livechat/chat-window-android#11]
### On API 18

> after integrating to an android app there wasn't any input field for sending messages

> I tried with your sample app it also didn't work as required

**Comment by nomyzs** [comment]
Hello @kesarawimal !

Sorry for late response but we just solved similar issue - #62 . So you might want to check if your problem is still present when using `v2.1.6` release.

Closing this for now, but please feel free to create another issue if you still experiencing any problems.
