### ISSUE TITLE
Hide chat issue

### ISSUE THREAD

**Issue by linescode** [livechat/chat-window-android#12]
Hi, I have integrated the mobile chat in our application, but when I hide the chat and reopen it, I have a console error and the chat is empty

chromium: [INFO: CONSOLE (0)] "Uncaught (in promise) # <Object>" , source: https://secure.livechatinc.com/licence/10259547/v2/open_chat.cgi?groups=null&webview_widget=1&native_platform=android (0)

but after a few minutes the chat works again.
The application is created by Nativescript, we work to write a plugin to integrate your native library

**Comment by nomyzs** [comment]
Hey @linescode!
First of all, thank you for your report and want to apologize to keep you waiting so long for so long.
The good news is that I think we have fixed this issue with version 2.0.4 of this widget.
So going to close this issue. 

Please don't hesitate to create a new one if you have issues or questions!
