### ISSUE TITLE
Client's chat window halted frozen?

### ISSUE THREAD

**Issue by exec228** [livechat/chat-window-android#13]
Hello!

Your chat-support directed us here to GitHub.

We are developing an app
https://play.google.com/store/apps/details?id=com.ntpayments.wallet
(currently closed testing)

LiveChat is used for customer support.

We met an unexpected feature
<a href='https://postimg.cc/s1tk294B' target='_blank'><img src='https://i.postimg.cc/s1tk294B/Screenshot-NT-Wallet-20190121-152523.png' border='0' alt='Screenshot-NT-Wallet-20190121-152523'/></a>
The chat is halted frozen, after back-end side employee closes this chat.

Client can restart the chat only after intentionally closing chat window.

How can we make it easier for client?
1) Don't block the chat window
2) Don't force a client to exit chat to re-enter

Thank you!
![screenshot_nt wallet_20190121-152523](https://user-images.githubusercontent.com/275328/51472718-bbd1d600-1d93-11e9-85e0-7315878a7fe5.png)

**Comment by konradk** [comment]
Hi @exec228 

Chat widget used in this application isn't our default web widget - it's probably custom widget build using [Visitor SDK](https://developers.livechatinc.com/docs/extending-ui/extending-chat-widget/visitor-sdk/) (legacy SDK) or [Customer SDK](https://developers.livechatinc.com/docs/extending-ui/extending-chat-widget/customer-sdk/). The described behavior is possible to achieve, but it needs to be done by the developer who created this widget.

Our default chat widget provides the possibility to start a chat again.

**Comment by nomyzs** [comment]
Thanks @konradk for the explanation!
