### ISSUE TITLE
Connection lost on chat window initiation

### ISSUE THREAD

**Issue by sag27** [livechat/chat-window-android#19]
Hi, I have integrated Livechat SDK with my android application. After integrating when I try to initiate chat 8/10 times it shows "Connection lost. Please check your internet connection and try again". But my internet strength is very strong but it keeps saying above issue. I am using trial version account and we are creating demo of LiveChat and chat bot integration in our product.

If such issue keeps on repeating we wont be able to integrate as it would be bad user experience. Please can the team look into it.

I have attached the video recording of issue
[20190322-122041-720x1280.zip](https://github.com/livechat/chat-window-android/files/2995317/20190322-122041-720x1280.zip)

**Comment by nomyzs** [comment]
Hello @sag27 👋 

Sorry for late response.
I wasn't able to reproduce this. Is this still happening to you? Do you have some additional info that could help to reproduce this issue?

**Comment by nomyzs** [comment]
Closing due to inability to reproduce this issue and inactivity.
Please create a new issue if problem is still present.

Best regards!
