### ISSUE TITLE
NOT SUPPORTED FOR 5+ VERSIONS

### ISSUE THREAD

**Issue by PremMayilai** [livechat/chat-window-android#2]
I have downloaded your code.It is working in 4.4 but not in 5+ version android.It is giving below log error.
07-05 14:53:02.841 3965-3965/com.livechatinc.livechatwidgetexample D/ViewRootImpl: ViewPostImeInputStage ACTION_DOWN
07-05 14:53:02.926 3965-3965/com.livechatinc.livechatwidgetexample I/Timeline: Timeline: Activity_launch_request id:com.livechatinc.livechatwidgetexample time:36463497
07-05 14:53:02.966 3965-3965/com.livechatinc.livechatwidgetexample D/Activity: performCreate Call secproduct feature valuefalse
07-05 14:53:02.971 3965-3965/com.livechatinc.livechatwidgetexample D/Activity: performCreate Call debug elastic valuetrue
07-05 14:53:03.001 3965-5667/com.livechatinc.livechatwidgetexample I/System.out: (HTTPLog)-Static: isSBSettingEnabled false
07-05 14:53:03.151 3965-3965/com.livechatinc.livechatwidgetexample I/cr_Ime: ImeThread is enabled.
07-05 14:53:03.151 3965-4575/com.livechatinc.livechatwidgetexample E/IMGSRV: :0: ComputeFrameBufferCompleteness: Switching psTex 0x9e6be480 to XBGR
07-05 14:53:03.156 3965-4575/com.livechatinc.livechatwidgetexample E/IMGSRV: :0: ComputeFrameBufferCompleteness: Switching psLevel 0xaf153400 to XBGR
07-05 14:53:03.156 3965-4575/com.livechatinc.livechatwidgetexample E/IMGSRV: :0: ComputeFrameBufferCompleteness: Switching psTex 0xaf185c00 to XBGR
07-05 14:53:03.161 3965-4575/com.livechatinc.livechatwidgetexample E/IMGSRV: :0: ComputeFrameBufferCompleteness: Switching psLevel 0xaf153c00 to XBGR
07-05 14:53:03.211 3965-4037/com.livechatinc.livechatwidgetexample D/OpenGLRenderer: endAllStagingAnimators on 0xb4cdf800 (RippleDrawable) with handle 0x9e3e30a0
07-05 14:53:03.266 3965-3965/com.livechatinc.livechatwidgetexample I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@2f60b2d2 time:36463836
07-05 14:53:03.476 3965-3965/com.livechatinc.livechatwidgetexample W/cr_BindingManager: Cannot call determinedVisibility() - never saw a connection for the pid: 3965
07-05 14:53:03.581 3965-3965/com.livechatinc.livechatwidgetexample V/ActivityThread: updateVisibility : ActivityRecord{368e14a4 token=android.os.BinderProxy@f3bf74c {com.livechatinc.livechatwidgetexample/com.livechatinc.livechatwidgetexample.MainActivity}} show : false

**Comment by nomyzs** [comment]
Hey @PremMayilai .
I just tested widget on Android API 22, 27 and 28. Everything seems to be fine.
Don't hesitate to open a new issue and provide more info on how to reproduce this issue if it still occurs on the latest chat-widget version.
