### ISSUE TITLE
Chat history not retained when launching from a new Activity using same/new ChatWindowConfiguration instance. 

### ISSUE THREAD

**Issue by akvivekrai** [livechat/chat-window-android#20]
I've chat icon on 3 different (Activity) screens in my app. If I have started a chat on one of these screens, and then go to another screen and launch chat there, it starts a fresh chat again and doesn't show my ongoing chat from the previous screen.
Unable to figure out how to retain chat history from one (Activity)screen to another.
I have tried reusing same ChatWindowConfiguration instance each time but no luck.

I am using full screen window as mentioned in https://developers.livechatinc.com/docs/android-widget/#full-screen-window

SAMPLE CODE:

```
ChatWindowView initializeFullScreenChat(Activity activity, ChatWindowView.ChatWindowEventsListener chatListener) {
        final ChatWindowConfiguration configuration = new ChatWindowConfiguration("licenseNumber", "random_group_id", null, null, null);

        ChatWindowView fullScreenChatWindow = ChatWindowView.createAndAttachChatWindowInstance(activity);
        fullScreenChatWindow.setUpWindow(configuration);
        fullScreenChatWindow.setUpListener(chatListener);
        fullScreenChatWindow.initialize();

        return fullScreenChatWindow;
    }

```

**Comment by nomyzs** [comment]
Hello @akvivekrai 

Which version of the widget are you using? Chat should retain its state, no matter how it's embedded since the 2.0.4 version. 
I wasn't able to reproduce it with the example app, so any tips on that would be appreciated :)
