### ISSUE TITLE
using Mobile Chat Widget for Android App Often show “Couldn\'t load chat.”

### ISSUE THREAD

**Issue by Jerrychengjun** [livechat/chat-window-android#22]
If I don't use livechat for 2 or 3 minutes in my App，
It will shows "Couldn\'t load chat."

The Website tells me that I can change the error message,But that's not what I need.
[LiveChat Docs](https://developers.livechatinc.com/docs/android-widget/#sample-application)
<string name="failed_to_load_chat">Couldn\'t load chat.</string>

I need to catch exception events，and complete retry function
![livechat_error](https://user-images.githubusercontent.com/49055094/55213874-b4192c80-522f-11e9-888b-6fcbf90c5a65.PNG)

**Comment by ZiggyKraus** [comment]
Hello @Jerrychengjun !

Thank you for reporting this problem! I will consult this case with our Android developer, and we will get back to you as soon as we have an update. We will also reach out in case of any additional questions that will help us with checking out why the chat couldn't be loaded on your Android application.

**Comment by nomyzs** [comment]
Hey @Jerrychengjun !
Hope you're doing well.
What do you think about the following changes:
https://github.com/livechat/chat-window-android/commit/115834d48745b71dc14b33d06375280445c5d4b9
Basically adding an `onError` function to chat window listener and passing there errors from WebView.

Will that suite your needs? Any feedback on that?

**Comment by bernardocampos** [comment]
I'm also having this issue. @Jerrychengjun did @nomyzs 's fix work for you?

**Comment by sagkissht** [comment]
I am facing similar issue and it's quite intermittent. Please can you solve it asap
![Screenshot_2019-07-05-12-06-35-710_com fastbanking](https://user-images.githubusercontent.com/52568817/60718568-a0721600-9f42-11e9-81ad-99878afd092f.png)

**Comment by nomyzs** [comment]
Please check out v2.1.0.
This should help with the problem above. The changes should also allow you to take full control of showing errors.
Hope it helps 🤞
