### ISSUE TITLE
Chat EditText Hiding behind the Keyboard

### ISSUE THREAD

**Issue by mukeshdadarwal** [livechat/chat-window-android#31]
In latest SDK version using your chat activity when keyboard appear  chat EditText hide issue
![processed](https://user-images.githubusercontent.com/19816408/74130957-52746d80-4c09-11ea-837c-decd611d3813.jpeg)
![processed](https://user-images.githubusercontent.com/19816408/74130972-5a341200-4c09-11ea-8950-d09ff676d720.jpeg)

**Comment by nomyzs** [comment]
Hello @mukeshdadarwal 

Could you answer the following questions to help us understand the problem:
1. Is chat window scrollable and you can scroll it to see input box?
2. On what Android version and device you experiencing this issue
3. How did you decide to implement Chat Window in your app, Embedded, own activity, within your own activity? Any code examples will be more helpful :)

Looking forward to these answers :)

**Comment by JohnGeorgiou** [comment]
Same issue here,
Both in fullscreen and embedded  chat windows the edittextview is hidden by the soft keyboard
I tried to put android:windowSoftInputMode="adjustResize|stateHidden" in the manifest / activity with no results

**Comment by nomyzs** [comment]
Hello @mukeshdadarwal and @JohnGeorgiou !

This issue should be solved in `v2.1.6` release.
Please refer to #62 for more details about the cause and implemented solution :)
