### ISSUE TITLE
ERROR: Failed to resolve: com.github.livechat:chat-window-android:v2.0.4

### ISSUE THREAD

**Issue by Marc-Ferrer-Castillo** [livechat/chat-window-android#32]
Hi, I have an error when trying to implement it in gradle like so:
```
dependencies {
    implementation 'com.github.livechat:chat-window-android:v2.0.4'
}
```

> **ERROR: Failed to resolve: com.github.livechat:chat-window-android:v2.0.4**

**Comment by Mastersam07** [comment]
Try using the below:

```
dependencies {
    implementation 'com.github.livechat:chat-window-android:v2.1.2'
}
```

**Comment by nomyzs** [comment]
Hello @Marc-Ferrer-Castillo 
I have tested that and seems alright with v2.0.4, v2.1.2 and v2.1.5.
Hopefully this is no longer an issue. Will close that issue, but please, feel free to create another one if issue persist
