### ISSUE TITLE
Chat EditText Hiding behind the Keyboard

### ISSUE THREAD

**Issue by AlmutawaEssam** [livechat/chat-window-android#33]
I am facing a problem in which the users can see the edit text once the soft keyboard appears, 

the same as here : https://github.com/livechat/chat-window-android/issues/31

I am using this method to implement the live chat: Full screen ChatWindow added to the root of your Activity

I tested this problem in most in devices on android and the same problem, S10+ for example

**Comment by AlmutawaEssam** [comment]
Any update on that issue?
https://ibb.co/PxMTB8n
https://ibb.co/7SYRGx6

**Comment by nomyzs** [comment]
Hey @AlmutawaEssam 
As responded in #62 issue should be solved in `v2.1.6` release
