### ISSUE TITLE
Certificate error on devices that ran LiveChat prior to 12/19/2017

### ISSUE THREAD

**Issue by j-rewerts** [livechat/chat-window-android#4]
The error:
Failed to validate the certificate chain, error: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

This only affects devices that had our app installed prior to a couple days ago.

**Comment by j-rewerts** [comment]
Let me know if you guys want this issue formatted a specific way or you want more detailed logs. 

Reproducing this issue is challenging, since it requires a device that ran LiveChat prior to 2 days ago.

**Comment by Jercik** [comment]
Hi, 
Yes, we would like more detailed logs. Specifically, what is the URL that returns this error?

**Comment by j-rewerts** [comment]
I've looked into this a little further, and I think this is probably our company's network set up. It looks like our wireless networks don't like Cisco as a CA for some reason. I'm tracking the issue [here](https://github.com/coe-google-apps-support/jazz-android/issues/7).

**Comment by j-rewerts** [comment]
Confirmed that this was an internal issue. Apologies.
