### ISSUE TITLE
ChatWindowConfiguration methods not recognized

### ISSUE THREAD

**Issue by Yatzzz** [livechat/chat-window-android#40]
In ChatWindowConfiguration class, setLicenceNumber() and setGroupId() is not public in  com.livechatinc.inappchat.ChatWindowConfiguration.Builder.

asBundle() is not recognized as well

```java
Intent intent = new Intent(this, ChatWindowActivity.class);
        Bundle config = new ChatWindowConfiguration.Builder()
                .setLicenceNumber("XXXXXXX")
                .setGroupId("X")
                .build()
                .asBundle();

        intent.putExtras(config);
```

https://github.com/livechat/chat-window-android#using-activity

**Comment by nomyzs** [comment]
Hey @Yatzzz 
Are you sure you used the latest library? That's true, those methods were note exposed but we fixed that in `v2.1.2`
