### ISSUE TITLE
NullPointerException at ChatWindowView.java line 365 com.livechatinc.inappchat.ChatWindowView.isSecureLivechatIncDoamin

### ISSUE THREAD

**Issue by anninosk** [livechat/chat-window-android#45]
I keep receiving this error, I updated to the latest version but it didnt really work.

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
com.livechatinc.inappchat.ChatWindowView.isSecureLivechatIncDoamin
`
is anyone having the same issue?

**Comment by kibrushi** [comment]
Any update with this issue? @anninosk

**Comment by nomyzs** [comment]
Fix by 
https://github.com/livechat/chat-window-android/commit/2af99afeb1a576b30e3e2a0c2d86033e9a571cce
