### ISSUE TITLE
Back navigation in ChatWindowView

### ISSUE THREAD

**Issue by SzymonGrochowiak** [livechat/chat-window-android#46]
Hi. I have a problem regarding the navigation through chat. I am using ChatWindowView and the back navigation doesn't work properly when the user opens some other window in the chat. For example, by opening an image in the conversation there is no way to go back to the conversation. It seems that chat WebView doesn't handle back navigation.

**Comment by nomyzs** [comment]
Hello!

I'm sorry for not getting back to you sooner. This is no longer an issue. Opening attachments is done now with an external browser, which should prevent any navigation issues.
Closing this issue, but feel free to contact us when you have any other feedback!
