### ISSUE TITLE
api 15 needed

### ISSUE THREAD

**Issue by int021h** [livechat/chat-window-android#5]
After adding livechat dependency to our build.gradle (complie 'com.github.livechat:chat-window-android:v2.0.3')
:processDebugManifest/:processReleaseManifest started to fail with 
Error: uses-sdk:minSdkVersion 15 cannot be smaller than version 16 declared in library [com.github.livechat:chat-window-android:v2.0.3] ~/.gradle/caches/transforms-1/files-1.1/chat-window-android-v2.0.3.aar/3b80e858f133c212ad12e862783ecfc4/AndroidManifest.xml as the library might be using APIs not available in 15

Our android app still supports minSdkVersion 15
While livechat's app/build.gradle declares minSdkVersion 16

1) Actually we can override minSdk while merging your AndroidManifest.xml with:
```
<uses-sdk android:minSdkVersion="15"
        tools:overrideLibrary="com.livechatinc.inappchat"
        />
```
and show livechat button only for "Build.VERSION.SDK_INT>=16" devices

or 
2) Decrease your minSdkVersion to 15 (if api 16's features are not so important for you)

**Comment by nomyzs** [comment]
Hey @int021h .
I think we can decrease min sdk version to 15. This should be included in the upcoming widget update.
