### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by therngbtg** [livechat/chat-window-android#53]
hi everyone, i want to use livechat for flutter, how to do it?

**Comment by shubham8170** [comment]
so if you want to build a chat app then you can use firebase's real-time database or you can use any real-time database.it will be easy or you can use a cryptography algorithm and your own database

**Comment by therngbtg** [comment]
> so if you want to build a chat app then you can use firebase's real-time database or you can use any real-time database.it will be easy or you can use a cryptography algorithm and your own database

No, firebase is ok, but i want to use LIVECHAT with flutter app,  https://www.livechat.com

**Comment by shubham8170** [comment]
Then you have to integrate AI with your flutter app.
You can follow mtechviral on YouTube

**Comment by Mastersam07** [comment]
Hello @therngbtg there is a flutter package for LiveChat available [here](https://pub.dev/packages/livechatt).

**Comment by abedelaziz-deriv** [comment]
@nomyzs we built this Flutter plugin https://pub.dev/packages/live_chat_plus

**Comment by nomyzs** [comment]
Thank you for your contributions. We now have options to choose from!:)
