### ISSUE TITLE
Allow initializing Chat Window with a Message

### ISSUE THREAD

**Issue by codekeyz** [livechat/chat-window-android#58]
```java
ChatWindowConfiguration(
  "your_licence_number",
  "group_id",
  "Visitor name",
  "visitor@email.com",
  customParamsMap
);
```

Is there a way i can parse a query during initialization?

**Comment by nomyzs** [comment]
Hello @codekeyz 
Thanks for reaching out.
I am not sure if understood your question correctly. But you can customise your welcome message in the web app in chat settings. See here:
[Agent Web App -> Settings -> Chat Widget -> Language](https://my.livechatinc.com/settings/language)

Hope that helps!

**Comment by nomyzs** [comment]
Hopefully this helped and solved your case @codekeyz . 
Closing this now, but feel to create new issue or reach me via email - s.jarosz@livechat.com
