### ISSUE TITLE
ChatWindowView at full screen obscured by activity bar and keyboard

### ISSUE THREAD

**Issue by kherink** [livechat/chat-window-android#59]
on some devices (many samsung phones including galaxy S8 and S9) the ChatWindowView is obscured by activity bar and keyboard after it is attached to existing activity and shown

**Top and input obscured (Samsung Galaxy S8, Android Version 9, Baseband Version G950FXXUCDUD1, One UI version 1)**
![Screenshot_20210521-153542_Luxury_Escapes_pixelated](https://user-images.githubusercontent.com/1751004/119419531-ce7ec000-bd3d-11eb-85bb-f0fb40f1554e.png)

**Top of the screen obscured (Pixel device)**
<img width="876" alt="Screen Shot 2021-05-24 at 11 55 31 am" src="https://user-images.githubusercontent.com/1751004/119301788-5dd89480-bca6-11eb-8022-82d56b949d92.png">

**Comment by kherink** [comment]
Hi @nomyzs,
thank you for following up. The 2 physical devices I was able to repro the issue are the listed S8, and a Google Pixel with Android 10. also a [S9](https://app.saucelabs.com/live/mobile/dataCenters/US/devices/Samsung_Galaxy_S9_free) (free test device provided by Sauce Labs on a test plan for their remote device farm) also on Android 10.
I am not aware of any special activity flag settings in the activity containing the chat view.
I've done exactly what you suggest and attached the ChatWindowView manually which worked fine for us.
Please let me know if you find anything based on the emailed info, or if i can be of futher help in investigating this.
Best regards,
Karel

**Comment by nomyzs** [comment]
Hey @kherink .
You might want to try `v2.1.6` version of this library.
Turns out your issues was reproducible when configuring parenting Activity in Full Screen Mode. PLease refer to #62 for more details :)

Thanks for your input on this! Hopefully this solves your problems and simplifies your integration :)
