### ISSUE TITLE
startActivityForResult is deprecated

### ISSUE THREAD

**Issue by kelian** [livechat/chat-window-android#74]
For example, in EmbeddedChatWindowFragmentExample.java the startActivityForResult and onActivityResult are deprecated methods. 

The new way to do it: https://developer.android.com/training/basics/intents/result

**Comment by Papashkin** [comment]
Any update?

**Comment by nomyzs** [comment]
Hello!
We have just released `v2.4.0rc1` where we moved away from the deprecated `startActivityForResult` for File Sharing.
It's not yet merged to master, but you can use a tag to try it out.

We hope it will solve your issue. 
We would appreciate any feedback you might have regarding the API.

**Comment by nomyzs** [comment]
We have released the changes
