### ISSUE TITLE
could not load chat Reload Chat error

### ISSUE THREAD

**Issue by aayushmaagrawal** [livechat/chat-window-android#76]
This error occurs randomly, when I press back from the live chat screen and again come back to the same screen.
![Screenshot_20220927-154627_Brainly](https://user-images.githubusercontent.com/110448287/192699190-76c4c261-3584-4c5b-a244-696d8f30ada4.jpg)

**Comment by nomyzs** [comment]
Hello!

Could you set up [Event Listener](https://github.com/livechat/chat-window-android#chatwindoweventslistener) and use it to get the error message and send it here?

I did try to close/open chat many times, but couldn't reproduce this.
Please also be mindful that the latest chat widget version is `2.2.1`

**Comment by nomyzs** [comment]
We will track this issue in #80
