### ISSUE TITLE
ChatWindowActivity input field not showing, Also sometimes chat is not able to launch.

### ISSUE THREAD

**Issue by pintu-elaunch** [livechat/chat-window-android#77]
When I open ChatWindowActivity for first time & start chat, I'm not getting input field to input message, But when I close & reopen chat window, the input field is getting visible. You can see the below image for reference: 

![LiveChatIssue1](https://user-images.githubusercontent.com/106513455/203110704-cf893c90-efd6-4618-bb29-824ba2e11d24.jpg)

Also sometimes the chat window is unable to load chat. I'm also attaching video for the issue below:

https://user-images.githubusercontent.com/106513455/203111083-73bdfbb4-e63a-4014-90e3-3dd3f0cbb6ae.mp4 

https://user-images.githubusercontent.com/106513455/203111094-9442ff57-e40f-4fbb-b9ac-461cbd1b38f5.mp4

**Comment by Reza-deriv** [comment]
The same issue here ...

**Comment by Reza-deriv** [comment]
-keep class com.livechatinc.inappchat.** { *; }

Fixed for me after adding this line to proguard-rules.pro
@pintu-elaunch

**Comment by nomyzs** [comment]
Hey @Reza-deriv and @pintu-elaunch 

Can you give more context to reproducing your problems? 
1. What Android version and device are you using?
2. Are you using ChatWindowActivity? Is there any specific activity configuration?
3. Can you see any errors in the logs?
4. Did you set `eventListener` when using Chat?

If you have not set the `eventListener` we would recommend trying it out. This will give you insights into errors coming from the integration and better control. It's possible that a non-critical error is thrown, closing the chat window and showing "Couldn't load chat" view. Handling it via `eventListener.onError` could keep chat operational. 

Please don't hesitate to send over any logs and errors you find. Any insights are appreciated!
Thanks in advance!
