### ISSUE TITLE
Always in Loading state, no error reported 

### ISSUE THREAD

**Issue by eagle1988china** [livechat/chat-window-android#78]
https://user-images.githubusercontent.com/7310762/233941674-0bb9aff5-0812-4657-9030-84fdf6235ab4.mov

Steps to reproduce:
1. Open Livechat
2. Turn off the network
3.Stay in the loading state, no error is reported
4. Close the livechat window and reopen it, it still stays in the loading state

**Comment by nomyzs** [comment]
We had a bug in reload logic. This was probably fixed with the `v2.3.2`. In case a problem persists, feel free to open a new issue.
