### ISSUE TITLE
Live Chat automatically closes when an agents accepts a chat or replies to a chat

### ISSUE THREAD

**Issue by emmannuelgozon24** [livechat/chat-window-android#79]
Hello Devs,

I'm experiencing an issue wherein everytime an agent accept a chat using the live chat portal the live chat window in the app automatically closes. Same thing happens when an agent replies to the chat.

Here's the error message I got from the logs.

on window errorType: Console errorCode: -1 description Uncaught Error: Java exception was raised during method invocation
INFO:CONSOLE(2)] "Uncaught Error: Java exception was raised during method invocation", source: https://cdn.livechatinc.com/widget/static/js/iframe.bae20d93.chunk.js

I'm hoping for your fast response.

Thanks!

**Comment by nomyzs** [comment]
Hello @emmannuelgozon24, could you try `v2.4.3` and check if the problem persists?

**Comment by nomyzs** [comment]
I reproduced this issue in `v2.4.2` and confirmed that it works as expected in `v2.4.3` and later versions.
