### ISSUE TITLE
Losing session when minimize the live chat window

### ISSUE THREAD

**Issue by HunkD** [livechat/chat-window-android#8]
Hi, I'm using ChatWindowActivity to present chat window. When press minimize button on Chat window, and back to ChatWindowActivity, it will lose the conversation at last time. 
Could you please share the knowledge that how live chat maintain the session, and bring it back from last time in sdk code？

**Comment by HunkD** [comment]
@rickymohan no, I didn't. Our company chooses another service provider.

**Comment by rickymohan** [comment]
Thanks @HunkD  for the reply, we ended up doing the same ..we finally used Intercom

**Comment by nomyzs** [comment]
Hello @HunkD and @rickymohan 
Sorry for lack of support on android chat widget so far. We are trying to improve on that nowadays.
However, in the meantime, we indeed found that issue you faced and fixed that with v2.0.4 version.

Thank you for reporting that. Don't hesitate to try LiveChat once more :)
