### ISSUE TITLE
Passing KEY_VISITOR_NAME and KEY_VISITOR_EMAIL doesn't work

### ISSUE THREAD

**Issue by kabuki5** [livechat/chat-window-android#9]
Hi, I'm trying to initialize chat window with autologin params ( user and email) to avoid use the "Pre-chat survey" but ever the login is with default user name "Client". I disabled the Pre-chat survey. I checked the params are passing well between LiveChat library activities but at the console I'm receiving "Client" like user name without email. 

Paste of my initialization code, in Kotlin, following the guide (https://docs.livechatinc.com/android-widget/#sample-usage) 

`val intent = Intent(this, ChatWindowActivity::class.java)
        intent.putExtra(com.livechatinc.inappchat.ChatWindowActivity.KEY_VISITOR_NAME, "Ramón")
        intent.putExtra(com.livechatinc.inappchat.ChatWindowActivity.KEY_VISITOR_EMAIL, "rbenmar@gmail.com")
        intent.putExtra(com.livechatinc.inappchat.ChatWindowActivity.KEY_LICENCE_NUMBER, BuildConfig.LIVECHAT_LICENSE_NUMBER)
        startActivity(intent)`

**Comment by nomyzs** [comment]
@kabuki5 
Thanks for reporting that. I have checked for this issue with the latest widget version and disabling pre-chat form in Agent's Web App. All params were showing in Details section about the visitor.
If this is still an issue for you, don't hesitate to open a new issue and provide information on how to reproduce that.
Thanks! :)
