### ISSUE TITLE
LiveChat not working without GSON proguard rules

### ISSUE THREAD

**Issue by p-dmitriy** [livechat/chat-window-android#96]
Hi!
After migration to kotlinx.serialization library we faced problem with live chat. It is not possible to start new chat with "no internet" error:
![telegram-cloud-photo-size-2-5307625696140583578-y](https://github.com/user-attachments/assets/9918bc86-de0d-4ba1-83d7-08d6b7b74d94)
But chat can be opened when you press "start chat", getting the error, then close and reopen chat.

After some research we figured out that the problem was in GSON ProGuard/R8 rules that was deleted when we migrated to kotlinx.serialization. Please mention in README that livechat requires those rules from host app and maybe you can show more meaningful error in this case. As I can see [here](https://github.com/livechat/chat-window-android/blob/27c131aca1a3cc9422cfe5c9be6152cb04c1b91b/inappchat/src/main/java/com/livechatinc/inappchat/ChatWindowJsInterface.java#L48) you deserialize NewMessage and not expect any exceptions, but they can be thrown if rules missing.

Seems #77 issue has same cause.

**Comment by p-dmitriy** [comment]
Or I think updating gson to 2.11.0, which provides proguard/r8 rules, can be enough to fix that.

**Comment by nomyzs** [comment]
Hey @p-dmitriy 
You are right. I managed to reproduce the issue by running the R8 in full mode. You will find a fix in `v2.4.3` release.
This was very helpful, thank you!
