### ISSUE TITLE
When will onError be triggered?

### ISSUE THREAD

**Issue by q80671428** [livechat/chat-window-android#98]
When I set licenseNo = '1', the chat window is opened and a license_not_found error appears. I noticed that there is an onError method on Android, but it is not triggered. Why is this? Finally, how can I catch this error on the iOS platform?

**Comment by nomyzs** [comment]
Hello!
Indeed, we haven't been reporting this error in the callback. We've made some changes to improve error handling in PR #99 and released a candidate: `v2.4.4rc1`. 

It aims to:
* allow for detecting HTTP errors, which will be fired in case of mentioned `license_not_found` error
* report only relevant or critical `ChatWindowErrorType.WebViewClient` errors in the `onError` callback
* provide a better explanation of the error types reported in the `onError` callback

Hopefully `v2.4.4rc1` helps you for now. Please try it out :)

As of now, we don't have an unambiguous way to identify `license_not_found`. We are working on the library rewrite and we will consider this case in the future, so your question is appreciated.

---

> Finally, how can I catch this error on the iOS platform?

Unfortunately, atm I don't know how you can catch this error in the iOS version. Have you tried [this](https://github.com/livechat/chat-window-ios?tab=readme-ov-file#handling-chat-window-errors)?
